/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Sweta Chowdhury
 */
public class StaffWorkAreaPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private StaffOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form StaffWorkAreaPanel
     */
    public StaffWorkAreaPanel(JPanel userProcessContainer, UserAccount account, StaffOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addEditStaffSkills = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        donateJButton2 = new javax.swing.JButton();
        donateJButton3 = new javax.swing.JButton();
        reportIncident = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO STAFF WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 41));

        addEditStaffSkills.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addEditStaffSkills.setText("ADD/EDIT INFORMATION");
        addEditStaffSkills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEditStaffSkillsActionPerformed(evt);
            }
        });
        add(addEditStaffSkills, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 300, 60));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("CREATE TRAINING CATALOG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 300, 50));

        donateJButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        donateJButton2.setText("MAKE A DONATION");
        add(donateJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 300, 53));

        donateJButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        donateJButton3.setText(" REQUEST MANAGEMENT");
        add(donateJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 300, 53));

        reportIncident.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reportIncident.setText("REPORT INCIDENT");
        reportIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIncidentActionPerformed(evt);
            }
        });
        add(reportIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 300, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void addEditStaffSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEditStaffSkillsActionPerformed
        AddEditInformationJPanel addEditStaffInfoJPanel = new AddEditInformationJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("addEditStaffInfoJPanel", addEditStaffInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addEditStaffSkillsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reportIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIncidentActionPerformed
        // TODO add your handling code here:
        IncidentReportingJPanel reportIncidentJPanel = new IncidentReportingJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("reportIncidentJPanel", reportIncidentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportIncidentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEditStaffSkills;
    private javax.swing.JButton donateJButton2;
    private javax.swing.JButton donateJButton3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reportIncident;
    // End of variables declaration//GEN-END:variables
}
