/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientAdmin;

import Business.Organization.PatientResgistryOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRegistry;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mamta
 */
public class PatientListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientListJPanel
     */
    private JPanel userProcessContainer; 
    private PatientResgistryOrganization organization;  
    private UserAccount account;
    public PatientListJPanel(JPanel userProcessContainer, UserAccount account, PatientResgistryOrganization organization ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        populateJTable();
    }
    
     public void populateJTable() {

        DefaultTableModel model = (DefaultTableModel) reqTbl.getModel();
        model.setRowCount(0);
            for (Patient patient : organization.getPatientDirectory().getPatientList() ) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = patient;
                row[1] = patient.getIndentification();
                row[2] = patient.getSynopsis();
                row[3] = patient.getGender();
                row[4] = patient.getRoom();

                model.addRow(row);
            }

    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reqTbl = new javax.swing.JTable();

        reqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name of Patient", "Identification Mark", "Synopsis ", "Gender", "Room Assigned"
            }
        ));
        jScrollPane1.setViewportView(reqTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reqTbl;
    // End of variables declaration//GEN-END:variables
}
