/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffAndVolunteerAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Member.Member;
import Business.Organization.StaffOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userinterface.HousingAdmin.ManageShelterJPanel.isValidEmail;

/**
 *
 * @author Sweta Chowdhury
 */
public class ViewStaffJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Member member;
    private ArrayList<String> skillSet = new ArrayList<String>();
    /**
     * Creates new form ViewStaffJPanel
     */
    public ViewStaffJPanel(JPanel userProcessContainer, Member member) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.member = member;
        populateInformation();
    }

    
   public void populateInformation() {
        memberType.setText(member.getType());
        nameJTextField.setText(member.getName());
        if (member.getPhoneNumber() != null) {
            phoneNumberJTextField.setText(member.getPhoneNumber());
        }

        if (member.getAddress() != null) {
            addressJTextField.setText(member.getAddress());
        }

        if (member.getGender() != null) {
            if (member.getGender().equals("Male")) {
                rdbMale.setSelected(true);
            } else {
                rdbFemale.setSelected(true);
            }
        }
        
        if (member.getEmail()!= null) {
           emailTextField.setText(member.getEmail());
        }
        

        if (member.getSkillSet() != null) {
            for (String skill : member.getSkillSet()) {
                if (skill.equals("AED")) {
                    chkAED.setSelected(true);
                }
                if (skill.equals("CNA")) {
                    chkCNA.setSelected(true);
                }
                if (skill.equals("CPR")) {
                    chkCPR.setSelected(true);
                }
                if (skill.equals("LGT")) {
                    chkLGT.setSelected(true);
                }
                if (skill.equals("FST")) {
                    chkFST.setSelected(true);
                }
                if (skill.equals("BLS")) {
                    chkBLS.setSelected(true);
                }
            }
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        phoneNumberJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chkCNA = new javax.swing.JCheckBox();
        chkAED = new javax.swing.JCheckBox();
        chkCPR = new javax.swing.JCheckBox();
        chkLGT = new javax.swing.JCheckBox();
        chkFST = new javax.swing.JCheckBox();
        chkBLS = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        memberType = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOtherSkills = new javax.swing.JTextField();
        chkNone = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 253, 208));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText(" STAFF INFORMATION SECTION");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 500, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Staff Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 131, 30));

        nameJTextField.setEditable(false);
        nameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 230, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Gender:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 110, 30));

        genderGroup.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.setEnabled(false);
        add(rdbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 90, -1));

        genderGroup.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rdbFemale.setText("Female");
        rdbFemale.setEnabled(false);
        add(rdbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 100, -1));

        phoneNumberJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(phoneNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 230, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Phone Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 131, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 131, 30));

        addressJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 230, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Skills Available:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 170, 30));

        chkCNA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkCNA.setText("Certified Nursing Assistant (CNA)");
        add(chkCNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        chkAED.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkAED.setText("Automated External Defibrillator (AED)");
        add(chkAED, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        chkCPR.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkCPR.setText("Cardiopulmonary Resuscitation (CPR)");
        chkCPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCPRActionPerformed(evt);
            }
        });
        add(chkCPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        chkLGT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkLGT.setText("Life Guard Trained");
        add(chkLGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        chkFST.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkFST.setText("Fire Service Trained");
        add(chkFST, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        chkBLS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkBLS.setText("Basic Life Support (BLS) Trained");
        add(chkBLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 160, 40));

        backButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 140, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Type:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));

        updateButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 150, 40));
        add(memberType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 230, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Email ID:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 30));
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 230, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Other Skills (if any):");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 170, 20));

        txtOtherSkills.setEditable(false);
        txtOtherSkills.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtOtherSkills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherSkillsActionPerformed(evt);
            }
        });
        add(txtOtherSkills, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 240, 30));

        chkNone.setText("None of the above");
        chkNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoneActionPerformed(evt);
            }
        });
        add(chkNone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void chkCPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCPRActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        boolean allowSave = true;
        
        allowSave = validateInputs();
        
        if(allowSave) {
             if (genderGroup.getSelection().equals(rdbMale.getModel())) {
            member.setGender("Male");
        } else if (genderGroup.getSelection().equals(rdbFemale.getModel())) {
            member.setGender("Female");
        }
        member.setPhoneNumber(phoneNumberJTextField.getText());
        member.setAddress(addressJTextField.getText());

        if (chkAED.isSelected()) {
            if (skillSet != null) {
                if (!skillSet.contains("AED")) {
                    skillSet.add("AED");
                }
            } else {
                skillSet.add("AED");
            }

        }

        if (chkCNA.isSelected()) {
            if (skillSet != null) {
                skillSet.add("CNA");
            } else {
                if (!skillSet.contains("CNAr")) {
                    skillSet.add("CNA");
                }
            }

        }

        if (chkCPR.isSelected()) {
            if (skillSet != null) {
                skillSet.add("CPR");
            } else {
                if (!skillSet.contains("CPR")) {
                    skillSet.add("CPR");
                }
            }
        }

        if (chkLGT.isSelected()) {
            if (skillSet != null) {
                skillSet.add("LGT");
            } else {
                if (!skillSet.contains("LGT")) {
                    skillSet.add("LGT");
                }
            }

        }

        if (chkFST.isSelected()) {
            if (skillSet != null) {
                skillSet.add("FST");
            } else {
                if (!skillSet.contains("FST")) {
                    skillSet.add("FST");
                }
            }
        }

        if (chkFST.isSelected()) {
            if (skillSet != null) {
                skillSet.add("FST");
            } else {
                if (!skillSet.contains("FST")) {
                    skillSet.add("FST");
                }
            }
        }

        if (chkBLS.isSelected()) {
            if (skillSet != null) {
                skillSet.add("BLS");
            } else {
                if (!skillSet.contains("BLS")) {
                    skillSet.add("BLS");
                }
            }
        }
        
        if (chkNone.isSelected()) {
                if (skillSet != null) {
                    if (!skillSet.contains(txtOtherSkills.getText())) {
                        skillSet.add(txtOtherSkills.getText());
                    }
                } else {
                    skillSet.add(txtOtherSkills.getText());
                }

            }

        member.setSkillSet(skillSet);

        JOptionPane.showMessageDialog(this, "Details updated successfully");
        }
        
       

    }//GEN-LAST:event_saveButtonActionPerformed

    public boolean validateInputs() {
        if (nameJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required");
            return false;
        } else {
            if (!validateStrings(nameJTextField.getText())) {
                return false;
            }
        }

        if (genderGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Gender is required");
            return false;
        }

        if (emailTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email ID is required.");
            return false;
        } else if (!isValidEmail(emailTextField.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email ID");
            return false;
        }

        if (phoneNumberJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Contact Number is required.");
            return false;
        } else if (phoneNumberJTextField.getText().matches("[0-9]+") == false) {
            JOptionPane.showMessageDialog(this, "Please enter a valid contact number.");
            return false;
        } else if (phoneNumberJTextField.getText().length() < 10) {
            JOptionPane.showMessageDialog(this, "Contact Number should be atleast 10 digits.");
            return false;
        }

        if (addressJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required.");
            return false;
        }

        if (chkNone.isSelected()) {
            if (txtOtherSkills.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Other Skills is required.");
                return false;
            }
        }

        return true;
    }

    public boolean validateStrings(String name) {
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter mandatory value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        Pattern pattern = Pattern.compile("[a-zA-Z ]*");
        Matcher matcher = pattern.matcher(name);
        if (!matcher.matches()) {

            JOptionPane.showMessageDialog(null, "Please enter valid string value", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component components[] = userProcessContainer.getComponents();
        for (Component component : components) {
            if (component instanceof ManageStaffJPanel) {
                ManageStaffJPanel mPanel = (ManageStaffJPanel) component;
                mPanel.populateJTable();
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void txtOtherSkillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherSkillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherSkillsActionPerformed

    private void chkNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoneActionPerformed
        // TODO add your handling code here:
        if (chkNone.isSelected()) {
            txtOtherSkills.setEnabled(true);
        } else {
            txtOtherSkills.setEnabled(false);
            txtOtherSkills.setText("");
        }
    }//GEN-LAST:event_chkNoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox chkAED;
    private javax.swing.JCheckBox chkBLS;
    private javax.swing.JCheckBox chkCNA;
    private javax.swing.JCheckBox chkCPR;
    private javax.swing.JCheckBox chkFST;
    private javax.swing.JCheckBox chkLGT;
    private javax.swing.JCheckBox chkNone;
    private javax.swing.JTextField emailTextField;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel memberType;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField phoneNumberJTextField;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField txtOtherSkills;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
