/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefOrgAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Incident.Incident;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ApproveDonationsJPanel extends javax.swing.JPanel {
    private JPanel container;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem system;
    /**
     * Creates new form ApproveDonationsJPanel
     */
    public ApproveDonationsJPanel(JPanel container, Enterprise enterprise, UserAccount account, EcoSystem system) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;
        this.account = account;
        this.system = system;
        populateTable();
    }

    
    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) donationRequests.getModel();
        model.setRowCount(0);

        for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[model.getColumnCount()];
                row[0] = request;
                row[1] = ((DonationWorkRequest) request).getDonationType();
                row[2] = request.getSender();
                row[3] = request.getReceiver();
                row[4] = request.getResolveDate();
                model.addRow(row);
        }
      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationRequests = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("APPROVE DONATIONS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 280, 41));

        donationRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(donationRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 130, 660, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable donationRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
