/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefOrgAdmin;

import Business.Incident.Incident;
import Business.Organization.Organization;
import javax.swing.JPanel;

/**
 *
 * @author Sweta Chowdhury
 */
public class ManageRequests extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequests
     */
    JPanel container;
    Incident incident;

    public ManageRequests(JPanel container, Incident incident) {
        initComponents();
        this.container = container;
        this.incident = incident;
        panelRaiseRequest.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRequests = new javax.swing.JTable();
        panelRaiseRequest = new javax.swing.JPanel();
        comboRequestType = new javax.swing.JComboBox();
        btnRaiseRequest = new javax.swing.JButton();
        noOfPeopleTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE REQUESTS FOR RELIEF ORGANIZATION ADMIN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 780, 41));

        jTblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Reciever", "Status"
            }
        ));
        jTblRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 620, 200));

        panelRaiseRequest.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "RAISE A NEW REQUEST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        panelRaiseRequest.setEnabled(false);

        comboRequestType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRaiseRequest.setText("MAKE REQUEST");
        btnRaiseRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseRequestActionPerformed(evt);
            }
        });

        jLabel2.setText("Request Type:");

        jLabel3.setText("Number of People:");

        javax.swing.GroupLayout panelRaiseRequestLayout = new javax.swing.GroupLayout(panelRaiseRequest);
        panelRaiseRequest.setLayout(panelRaiseRequestLayout);
        panelRaiseRequestLayout.setHorizontalGroup(
            panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaiseRequestLayout.createSequentialGroup()
                .addGroup(panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRaiseRequestLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noOfPeopleTextField)
                            .addComponent(comboRequestType, 0, 190, Short.MAX_VALUE)))
                    .addGroup(panelRaiseRequestLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnRaiseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(226, 226, 226))
        );
        panelRaiseRequestLayout.setVerticalGroup(
            panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaiseRequestLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRequestType, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRaiseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfPeopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnRaiseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        add(panelRaiseRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 430, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void jTblRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRequestsMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTblRequests.getSelectedRow();
        if (selectedRow >= 0) {
            panelRaiseRequest.setVisible(true);
        } else {
            panelRaiseRequest.setVisible(false);
        }
    }//GEN-LAST:event_jTblRequestsMouseClicked

    private void btnRaiseRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseRequestActionPerformed
        // TODO add your handling code here:
//      if(comboRequestType.getSelectedItem().equals(Organization.OrganizationType.))
    }//GEN-LAST:event_btnRaiseRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaiseRequest;
    private javax.swing.JComboBox comboRequestType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRequests;
    private javax.swing.JTextField noOfPeopleTextField;
    private javax.swing.JPanel panelRaiseRequest;
    // End of variables declaration//GEN-END:variables
}
