/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WarehouseAdmin;

import Business.EcoSystem;
import userinterface.ShelterOrgAdmin.*;
import Business.Enterprise.Enterprise;
import Business.Items.Item;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HousingWorkRequest;
import Business.WorkQueue.WarehouseRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prathamesh Tambe
 */
public class ManageRequestsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private WarehouseOrganization org;
    private UserAccount account;
    private EcoSystem business;

    /**
     * Creates new form ManageRequestsJPanel
     */
    public ManageRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;

        populateJTable();

        requestsJTable.getColumnModel().getColumn(8).setMinWidth(0);
        requestsJTable.getColumnModel().getColumn(8).setMaxWidth(0);
    }

    public void populateJTable() {

        DefaultTableModel model = (DefaultTableModel) requestsJTable.getModel();
        model.setRowCount(0);

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof WarehouseOrganization) {
                this.org = (WarehouseOrganization) org;
                for (WorkRequest req : org.getWorkQueue().getWorkRequestList()) {
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = req;
                    row[1] = ((WarehouseRequest) req).getQty();
                    row[2] = req.getReceiver();
                    row[3] = req.getSender();
                    row[4] = req.getRequestDate();
                    row[5] = req.getStatus();
                    row[6] = req.getResolveDate();
                    row[7] = ((WarehouseRequest) req).getRemaining();
                    row[8] = ((WarehouseRequest) req).getItem();
                    model.addRow(row);
                }

            }
        }
        
        for(WorkRequest req: account.getWorkQueue().getWorkRequestList()) {
             Object[] row = new Object[model.getColumnCount()];
                    row[0] = req;
                    row[1] = ((WarehouseRequest) req).getQty();
                    row[2] = req.getReceiver();
                    row[3] = req.getSender();
                    row[4] = req.getRequestDate();
                    row[5] = req.getStatus();
                    row[6] = req.getResolveDate();
                    row[7] = ((WarehouseRequest) req).getRemaining();
                    row[8] = ((WarehouseRequest) req).getItem();
                    model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestsJTable = new javax.swing.JTable();
        approveButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        requestItems = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 253, 208));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("MANAGE REQUESTS FOR WAREHOUSE ADMIN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 41));

        requestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Type", "Quantity", "Receiver", "Sender", "Request Date", "Status", "Approved Date", "Remaining", "Item"
            }
        ));
        jScrollPane1.setViewportView(requestsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 930, 170));

        approveButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        approveButton.setText("Approve Request");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });
        add(approveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 210, 40));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/arrow-back-icon_1_40x40.png"))); // NOI18N
        backJButton.setContentAreaFilled(false);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 50));

        requestItems.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        requestItems.setText("Request stock");
        requestItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestItemsActionPerformed(evt);
            }
        });
        add(requestItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] components = userProcessContainer.getComponents();
        for (Component component : components) {
            if (component instanceof ManageItemsJPanel) {
                ManageItemsJPanel items = (ManageItemsJPanel) component;
                items.populateTable();
            }
        }
    }//GEN-LAST:event_backJButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        int remaining = 0;
        if (requestsJTable.getSelectedRow() >= 0) {
            if (!requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 5).toString().equals("Approved")) {
                if (requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 5).toString().equals("Requested")) {
                    JOptionPane.showMessageDialog(this, "You can approve your own request");
                } else {
                    if ((Integer) requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 7) > 0) {
                        WorkRequest req = (WarehouseRequest) requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 0);
                        req.setReceiver(account);
                        req.setStatus("Approved");
                        req.setResolveDate(new Date());
                        if (((WarehouseRequest) req).getRemaining() - (Integer) requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 1) < 0) {
                            remaining = 0;

                        } else {
                            remaining = ((WarehouseRequest) req).getRemaining() - (Integer) requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 1);
                        }

                        ((WarehouseRequest) req).setRemaining(remaining);

                        if (requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 8) != null) {
                            Item item = (Item) requestsJTable.getValueAt(requestsJTable.getSelectedRow(), 8);
                            if (item != null) {
                                item.setQty(((WarehouseRequest) req).getRemaining());
                            }
                        }
                        populateJTable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Out of stock!");
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Request already approved");

            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select an item");
        }


    }//GEN-LAST:event_approveButtonActionPerformed

    private void requestItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestItemsActionPerformed
        // TODO add your handling code here:
        RequestStockJPanel requestStockItemsJPanel = new RequestStockJPanel(userProcessContainer, enterprise, account, business);
        userProcessContainer.add("requestStockItemsJPanel", requestStockItemsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_requestItemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requestItems;
    private javax.swing.JTable requestsJTable;
    // End of variables declaration//GEN-END:variables
}
