/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DisasterVictimRegistry;

import Business.DisasterRegistry.DisasterVictim;
import Business.Organization.DisasterVictimOrganization;
import Business.WorkQueue.MissingPersonRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mamta
 */
public class ProcessMissingPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessMissingPersonJPanel
     */
    private JPanel userProcessContainer;
    private MissingPersonRequest request;
    private DisasterVictimOrganization organization;

    public ProcessMissingPersonJPanel(JPanel userProcessContainer, MissingPersonRequest request, DisasterVictimOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        populateTable();
        String search = "";
        searchTxt.setText(request.getPersonName());
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) victimTbl.getModel();
        model.setRowCount(0);
        System.out.println("outside");
        for (DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
            System.out.println("in");
            if (dv.getType().equals("Missing Person")) {
                System.out.println("inside");
                Object[] row = new Object[model.getColumnCount()];
                row[0] = dv;
                row[1] = dv.getAge();
                row[2] = dv.getGender();
                row[3] = dv.getAddress();
                row[4] = dv.getContact();
                row[5] = dv.getNationality();
                row[6] = dv.getType();
                model.addRow(row);
            }
        }
    }
        //if(victimCombo.getSelectedItem().equals("Missing Person")){
//            for(DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
//                if(dv.getType().equals("Missing Person")){
//                    Object[] row = new Object[model.getColumnCount()];
//                    row[0] = dv;
//                    row[1] = dv.getAge();
//                    row[2] = dv.getGender();
//                    row[3] = dv.getAddress();
//                    row[4] = dv.getContact();
//                    row[5] = dv.getNationality();
//                    row[6] = dv.getType();
//                    model.addRow(row);
//                } 
    //   } 

    public void populateTables(String search) {
        DefaultTableModel model = (DefaultTableModel) victimTbl.getModel();
        model.setRowCount(0);
        System.out.println("outside");
        for (DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
            System.out.println("in");
          //  if (dv.getType().equals("Missing Person")) {
                if (search.equals(request.getPersonName())) {
                    System.out.println("inside");
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = search;
                    row[1] = dv.getAge();
                    row[2] = dv.getGender();
                    row[3] = dv.getAddress();
                    row[4] = dv.getContact();
                    row[5] = dv.getNationality();
                    row[6] = dv.getType();
                    model.addRow(row);
                }
            //}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        victimTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 253, 208));

        victimTbl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        victimTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Address", "Contact", "Nationality", "Type"
            }
        ));
        jScrollPane1.setViewportView(victimTbl);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/arrow-back-icon_1_40x40.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (searchTxt.getText().equalsIgnoreCase(request.getPersonName())) {
            populateTables(searchTxt.getText());
        }
        if (searchTxt.getText().equalsIgnoreCase(request.getPersonName()) || searchTxt.getText().equalsIgnoreCase(request.getGender()) || searchTxt.getText().equalsIgnoreCase(request.getAddress())
                || searchTxt.getText().equalsIgnoreCase(request.getMessageTpe())) {
            populateTables(searchTxt.getText());
        }
//        if((search.equalsIgnoreCase(request.getPersonName())) || (search.equalsIgnoreCase(request.getMessageTpe())) || (search.equalsIgnoreCase(request.getGender()))
//                (search.equalsIgnoreCase(request.getAddress()))){
//        
//    }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable victimTbl;
    // End of variables declaration//GEN-END:variables
}
