/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DisasterVictimRegistry;

import Business.DisasterRegistry.DisasterVictim;
import Business.Organization.DisasterVictimOrganization;
import Business.WorkQueue.MissingPersonRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mamta
 */
public class ProcessMissingPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessMissingPersonJPanel
     */
    private JPanel userProcessContainer;
    private MissingPersonRequest request;
    private DisasterVictimOrganization organization;
    public ProcessMissingPersonJPanel(JPanel userProcessContainer, MissingPersonRequest request,DisasterVictimOrganization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        this.organization=organization;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) victimTbl.getModel();
        model.setRowCount(0);
    
        for(DisasterVictim dv: organization.getDisasterVictimDirectory().getVictimList()){
            if(dv.getType().equals(request)){
                Object[] row = new Object[model.getColumnCount()];
                    row[0] = dv;
                    row[1] = dv.getAge();
                    row[2] = dv.getGender();
                    row[3] = dv.getAddress();
                    row[4] = dv.getContact();
                    row[5] = dv.getNationality();
                    row[6] = dv.getType();
                    model.addRow(row);
            }
            
        }
        //if(victimCombo.getSelectedItem().equals("Missing Person")){
//            for(DisasterVictim dv : organization.getDisasterVictimDirectory().getVictimList()) {
//                if(dv.getType().equals("Missing Person")){
//                    Object[] row = new Object[model.getColumnCount()];
//                    row[0] = dv;
//                    row[1] = dv.getAge();
//                    row[2] = dv.getGender();
//                    row[3] = dv.getAddress();
//                    row[4] = dv.getContact();
//                    row[5] = dv.getNationality();
//                    row[6] = dv.getType();
//                    model.addRow(row);
//                } 
     //   } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        victimTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        victimTbl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        victimTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Address", "Contact", "Nationality", "Type"
            }
        ));
        jScrollPane1.setViewportView(victimTbl);

        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable victimTbl;
    // End of variables declaration//GEN-END:variables
}
